In [117]:
import pandas as pd

df = pd.read_csv("/home/sonu/code/ml/phisingdetector/data/urls1.csv")
df.head()

,URL,url_length,has_ip_address,dot_count,https_flag,url_entropy,token_count,subdomain_count,query_param_count,tld_length,path_length,has_hyphen_in_domain,number_of_digits,tld_popularity,suspicious_file_extension,domain_name_length,percentage_numeric_chars,ClassLabel
0,https://keraekken-loagginnusa.godaddysites.com/,47,0,2,1,4.250669,6,1,1,3,1,1,0,1,0,12,0.0,0.0
1,https://metamsk01lgiix.godaddysites.com/,40,0,2,1,4.196439,6,1,1,3,1,0,2,1,0,12,5.0,0.0
2,http://myglobaltech.in/,23,0,1,0,3.936180,5,0,1,2,1,0,0,0,0,12,0.0,0.0
3,http://djtool-for-spotify.com/,30,0,1,0,3.894740,5,0,1,3,1,1,0,1,0,18,0.0,0.0
4,https://scearmcoommunnlty.com/invent/freind/get,47,0,1,1,4.143127,7,0,1,3,18,0,0,1,0,17,0.0,0.0

In [118]:
df.shape

(101219, 18)

In [119]:
df.columns

Index(['URL', 'url_length', 'has_ip_address', 'dot_count', 'https_flag',
       'url_entropy', 'token_count', 'subdomain_count', 'query_param_count',
       'tld_length', 'path_length', 'has_hyphen_in_domain', 'number_of_digits',
       'tld_popularity', 'suspicious_file_extension', 'domain_name_length',
       'percentage_numeric_chars', 'ClassLabel'],
      dtype='str')

In [120]:
our_df=df[["URL","ClassLabel"]].copy()

In [121]:
our_df["ClassLabel"].value_counts(normalize=True)

ClassLabel
0.0    0.629117
1.0    0.370883
Name: proportion, dtype: float64

In [122]:
our_df.isnull().sum()

URL           0
ClassLabel    1
dtype: int64

In [123]:
our_df["URL"].duplicated().sum()

np.int64(346)

In [124]:
our_df=our_df.drop_duplicates()

In [125]:
our_df.duplicated().sum()

np.int64(0)

In [126]:
our_df=our_df.reset_index(drop=True)

In [127]:
url=our_df["URL"].iloc[0]
print(url)
print("length:", len(url))

https://keraekken-loagginnusa.godaddysites.com/
length: 47

In [128]:
print("dots:", url.count("."))
print("slashes:" , url.count("/"))
print("hyphens:", url.count("-"))
print("digits:", sum(c.isdigit() for c in url))

dots: 2
slashes: 3
hyphens: 1
digits: 0

In [129]:


import os
print(os.listdir("../src"))

['predict.py', '__pycache__', 'feature_extraction.py']

In [130]:
import sys
sys.path.append("..")

In [131]:
import importlib
import src.feature_extraction

importlib.reload(src.feature_extraction)

extract_features = src.feature_extraction.extract_features

In [132]:

import joblib
import sys
from pathlib import Path

project_root = Path.cwd().resolve().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.feature_extraction import extract_features

_joblib = joblib

In [133]:
extract_features(url)

{'url_length': 47,
 'dots': 2,
 'hyphens': 1,
 'digits': 0,
 'slashes': 3,
 'question_marks': 0,
 'equal_signs': 0,
 'at_symbol': 0,
 'ampersand': 0,
 'percent': 0,
 'underscore': 0,
 'tilde': 0,
 'scheme_len': 5,
 'hostname_len': 38,
 'query_len': 0,
 'fragment_len': 0,
 'path_len': 1,
 'has_query': 0,
 'has_fragment': 0,
 'has_https': 1,
 'has_www': 0,
 'has_port': 0,
 'num_subdomains': 1,
 'has_ip_address': 0,
 'has_punycode': 0,
 'num_encoded_chars': 0,
 'suspicious_word_count': 0,
 'url_entropy': 4.250669436461801,
 'domain_entropy': 3.970840013101985,
 'path_entropy': -0.0,
 'digit_ratio': 0.0,
 'letter_ratio': 0.851063829787234,
 'special_char_ratio': 0.14893617021276595,
 'max_special_run': 3}

In [134]:

features = pd.DataFrame([extract_features(x) for x in our_df["URL"]])

In [135]:
features.head()

,url_length,dots,hyphens,digits,slashes,question_marks,equal_signs,at_symbol,ampersand,percent,...,has_punycode,num_encoded_chars,suspicious_word_count,url_entropy,domain_entropy,path_entropy,digit_ratio,letter_ratio,special_char_ratio,max_special_run
0,47,2,1,0,3,0,0,0,0,0,...,0,0,0,4.250669,3.970840,-0.000000,0.00,0.851064,0.148936,3
1,40,2,0,2,3,0,0,0,0,0,...,0,0,0,4.196439,3.953566,-0.000000,0.05,0.800000,0.150000,3
2,23,1,0,0,3,0,0,0,0,0,...,0,0,0,3.936180,3.773557,-0.000000,0.00,0.782609,0.217391,3
3,30,1,2,0,3,0,0,0,0,0,...,0,0,1,3.894740,3.658993,-0.000000,0.00,0.766667,0.233333,3
4,47,1,0,0,5,0,0,0,0,0,...,0,0,0,4.143127,3.463281,3.155222,0.00,0.851064,0.148936,3

In [136]:
y=our_df["ClassLabel"]

In [137]:
print("features shape:", features.shape)
print("labels shape:", y.shape)

features shape: (100873, 34)
labels shape: (100873,)

In [138]:
features.describe()

,url_length,dots,hyphens,digits,slashes,question_marks,equal_signs,at_symbol,ampersand,percent,...,has_punycode,num_encoded_chars,suspicious_word_count,url_entropy,domain_entropy,path_entropy,digit_ratio,letter_ratio,special_char_ratio,max_special_run
count,100873.000000,100873.000000,100873.000000,100873.000000,100873.000000,100873.000000,100873.000000,100873.00000,100873.000000,100873.000000,...,100873.000000,100873.000000,100873.000000,100873.000000,100873.000000,100873.000000,100873.000000,100873.000000,100873.000000,100873.000000
mean,35.030405,3.008535,0.100354,8.508788,2.837360,0.008278,0.017507,0.00005,0.011648,0.020154,...,0.000149,0.020154,0.032576,3.975920,3.043891,1.713392,0.241332,0.532226,0.226440,2.983157
std,16.781886,0.946061,0.519612,8.545658,0.863157,0.095090,0.246939,0.00704,0.214781,0.498014,...,0.012193,0.498014,0.216245,0.307131,0.480200,1.573637,0.224899,0.264138,0.051353,0.249084
min,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.521641,1.469309,0.000000,0.000000,0.122449,0.000000,0.000000
25%,27.000000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,3.770942,2.661226,0.000000,0.000000,0.264706,0.179104,3.000000
50%,31.000000,3.000000,0.000000,10.000000,3.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,3.936892,2.968919,1.000000,0.196429,0.634615,0.238095,3.000000
75%,35.000000,4.000000,0.000000,15.000000,3.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,4.100229,3.468577,2.807355,0.470588,0.791667,0.272727,3.000000
max,474.000000,19.000000,23.000000,164.000000,18.000000,3.000000,13.000000,1.00000,13.000000,83.000000,...,1.000000,83.000000,5.000000,5.871503,4.854766,5.671992,0.659574,1.000000,0.368421,19.000000

In [139]:
print(features.dtypes)

url_length                 int64
dots                       int64
hyphens                    int64
digits                     int64
slashes                    int64
question_marks             int64
equal_signs                int64
at_symbol                  int64
ampersand                  int64
percent                    int64
underscore                 int64
tilde                      int64
scheme_len                 int64
hostname_len               int64
query_len                  int64
fragment_len               int64
path_len                   int64
has_query                  int64
has_fragment               int64
has_https                  int64
has_www                    int64
has_port                   int64
num_subdomains             int64
has_ip_address             int64
has_punycode               int64
num_encoded_chars          int64
suspicious_word_count      int64
url_entropy              float64
domain_entropy           float64
path_entropy             float64
digit_ratio              float64
letter_ratio             float64
special_char_ratio       float64
max_special_run            int64
dtype: object

In [140]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

mask = y.notna()
X = features.loc[mask].reset_index(drop=True)
y_clean = y.loc[mask].astype(int).reset_index(drop=True)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_clean,
    test_size=0.2,
    random_state=42,
    stratify=y_clean
)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

pca = PCA(n_components=0.95)

X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

In [141]:
import joblib

joblib.dump(scaler, "../models/scaler.pkl")
joblib.dump(pca, "../models/pca.pkl")

['../models/pca.pkl']

In [142]:
pca_columns = [f"PC{i+1}" for i in range(X_train_pca.shape[1])]

X_train_pca_df = pd.DataFrame(
    X_train_pca,
    columns=pca_columns
)

X_test_pca_df = pd.DataFrame(
    X_test_pca,
    columns=pca_columns
)

X_train_pca_df.to_csv("x_train_pca.csv", index=False)
X_test_pca_df.to_csv("x_test_pca.csv", index=False)

y_train.to_csv("y_train.csv", index=False)
y_test.to_csv("y_test.csv", index=False)

In [143]:
print("Original features:", X_train.shape[1])
print("PCA features:", X_train_pca.shape[1])
print("Variance retained:", pca.explained_variance_ratio_.sum())

Original features: 34
PCA features: 16
Variance retained: 0.9526083272778723

In [144]:
print("Total URLs:", len(df))
print("Unique URLs:", df["URL"].nunique())
print("Duplicate URLs:", df["URL"].duplicated().sum())

Total URLs: 101219
Unique URLs: 100873
Duplicate URLs: 346